Meyfarth\CrontaskBundle\Entity\Crontask:
    type: entity
    table: meyfarth_crontask
    repositoryClass: Meyfarth\CrontaskBundle\Repository\CrontaskRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        commands:
            type: array
        commandInterval:
            type: integer
            column: command_interval
        intervalType:
            type: smallint
            column: interval_type
        firstRun:
            type: datetime
            column: first_run
        lastRun:
            type: datetime
            column: last_run
            nullable: true
        isActive:
            type: boolean
            column: is_active
    lifecycleCallbacks: {  }
