services:
#    meyfarth_crontask.example:
#        class: Meyfarth\CrontaskBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    meyfarth.form.crontask:
        class: Meyfarth\CrontaskBundle\Form\Type\CrontaskType
        tags:
            - { name: form.type, alias: meyfarth_crontask }